### ISSUE TITLE
Setting YOAST_ENVIRONMENT development breaks scripts loading

### ISSUE THREAD

**Issue by tcrsavage** [humanmade/altis-seo#148]
Steps to reproduce:
1. Install yoast seo premium
2. Load post list screen in admin
3. Check browser console warnings

![brokenyoastscripts](https://user-images.githubusercontent.com/907521/142195531-734dd0a5-4c85-412f-a949-4487dd905880.png)

Bug caused by 'enable_yoast_development_mode', which causes yoast seo to try to load non-minified scripts, which are not bundled with yoast seo premium.

**Comment by roborourke** [comment]
Just to confirm this on the dev environment only?
