### ISSUE TITLE
Migrate command processes every post object on the site

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/altis-seo#149]
While upgrading to Altis v9, running `altis migrate` in a local environment with a recently refreshed database from an Altis project with approximately 19k published posts caused 361,017 post objects to be processed while "Migrating legacy SEO settings" and took almost 2 hours to run to completion. The query within the `migrate_wpseo_to_yoast` function is returning every single post object on the site, including revisions and oembed caches.

The site in question has been using Yoast Premium for years, and never relied on the legacy Altis SEO module. If I query the database directly, I see no meta keys matching our target `$old` values in the [`meta_mapping` object](https://github.com/humanmade/altis-seo/blob/master/inc/namespace.php#L511-L515). _e.g._,

```
select count(*) from wp_postmeta where meta_key="_meta_title";
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```

The reason things are taking so long to run is the `meta_query` we execute within that `migrate_wpseo_to_yoast()` function:

```php
	'meta_query' => [
		'relation' => 'OR',
		[
			'meta_key' => '_meta_title',
			'meta_compare' => 'EXISTS',
		],
		[
			'meta_key' => '_meta_description',
			'meta_compare' => 'EXISTS',
		],
		[
			'meta_key' => '_meta_keywords',
			'meta_compare' => 'EXISTS',
		],
	],
```
Note that we're using `meta_key` and `meta_compare` in the nested arrays. If I am reading the [wp meta query docs](https://developer.wordpress.org/reference/classes/wp_meta_query/#accepted-arguments) properly, those keys are only accepted in the `meta_query` array itself, and nested arrays should be using `key` and `compare`, _e.g._

```php
	[
		'key' => '_meta_keywords',
		'compare' => 'EXISTS',
	],
```

Because of this difference between the expected arguments and what we are providing, I believe the current query is stripping all meta query comparisons and returning every post on every site. This will result in a LOT of unnecessary processing while upgrading to Altis 9, because the migration routine then goes through the entire site and tries to find each of those three keys on every single post object (none of which have them), to no actual benefit.

You can validate that the `meta_key` is being ignored and returning all posts by trying this query locally in `wp shell`:
```php
// Handle post meta.
$posts_query_args = [
    'post_type' => 'post',
    'post_status' => 'any',
    'posts_per_page' => 0,
    'fields' => 'ids',
    'suppress_filters' => true,
    'meta_query' => [
        'relation' => 'OR',
        [
            'meta_key' => '2014 SUBARU IMPREZA WRX Hatch, Premium trim, 32k miles',
            'meta_compare' => 'EXISTS',
        ],
    ],
];
$posts = new WP_Query( $posts_query_args );

// Will log however many posts you have.
WP_CLI::log( $posts->found_posts );
```

Switching these meta parameters to `key` and `compare` may not fix the issue, because I made those changes locally and started running that query 30 minutes ago and it still hasn't completed. A triple-barrel EXISTS `meta_compare` on a medium-to-large site appears to be paralyzingly slow. (In my testing, only querying for a single `EXISTS` meta query at a time was any kind of fast.) However, I suspect that if it does complete, it will correctly detect that no posts in the site actually have these keys present.

This is a pretty big issue with the Altis 9 upgrade path.

Acceptance criteria:

- [ ] Only posts with old WP SEO meta keys present get processed when running the Altis SEO migration routine.
- [ ] The migration command runs in a reasonable amount of time

**Comment by roborourke** [comment]
Whoops 😬 missed that in the review
