### ISSUE TITLE
`og:article:author` opengraph property should be `article:author`

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-seo#163]
In https://github.com/humanmade/altis-seo/blob/master/inc/opengraph/class-author-presenter.php we add the `og:article:author` tag, however from what I can see, this is not an opengraph tag. Looking at https://stackoverflow.com/questions/29748013/what-is-the-correct-implementation-of-the-open-graph-article-type, this should be just `article:author`. Also, check the same when using this tool: https://webcode.tools/generators/open-graph/article

**Comment by joehoyle** [comment]
It does seem Yoast also has a `Article_Author_Presenter`, but I can't find for the life of me how / if that's actually used.

**Comment by roborourke** [comment]
Can you make the issue title more descriptive please!

Anyway, I think it's a holdover from the legacy opengraph plugin, part of the migration to Yoast was not to lose any data.
