### ISSUE TITLE
Preserve URL parameters

### ISSUE THREAD

**Issue by robindevitt** [humanmade/altis-seo#173]
### Issue 
Currently the [HM Redirects](https://github.com/humanmade/hm-redirects) plugin doesn't support URL's with parameters. So when setting up a redirect, the user can only set `old-url` to  redirect to `new-url`.

So when the complete url `https://dev.altis.dev/old-url/?utm_content=search` contains a parameter it won't redirect accordingly and it will cause a 404 error.

### Accepted Criteria
Ensure that when a url contains a parameter, that the parameters are preserved in the redirect.
EG: `https://dev.altis.dev/old-url/?utm_content=search` redirects to `https://dev.altis.dev/new-url/?utm_content=search`

### GitHub
Current Issue https://github.com/humanmade/hm-redirects/issues/33
Pull request https://github.com/humanmade/hm-redirects/pull/55

**Comment by robindevitt** [comment]
Task has been posted for a review in slack.

**Comment by joehoyle** [comment]
Just to note we have this as an ongoing with a large customer. The primary issue is that redirects don't work when a URL param is added (not to the redirect its self).

**Comment by roborourke** [comment]
You should be able to update to the latest patch version now @joehoyle

**Comment by robindevitt** [comment]
Referencing the slack thread that is relevant to this issue: https://hmn.slack.com/archives/C3CKS8LLR/p1642672742223700
