### ISSUE TITLE
Allow installing facebook-instant-articles-wp with stable minimum-stability flag?

### ISSUE THREAD

**Issue by goldenapples** [humanmade/altis-seo#19]
I'm not 100% sure where the best place to raise this issue is. Trying to install altis without a `"minimum-stability": "RC"` specified, I get errors when composer tries to install altis/seo:

```
➜  platform-site git:(upgrade-altis-to-1.0.0) ✗ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Removal request for altis/seo == 1.0.0.0-RC3
    - Conclusion: remove humanmade/facebook-instant-articles-wp 4.2.1+hm
    - Removal request for altis/altis == 1.0.0.0-RC3
    - Installation request for altis/altis ^1.0 -> satisfiable by altis/altis[1.0.0, 1.0.0-rc3].
    - altis/altis 1.0.0 requires altis/seo ^1.0.0 -> satisfiable by altis/seo[1.0.0-rc3, 1.0.0, 1.0.1].
    - altis/seo 1.0.1 requires humanmade/facebook-instant-articles-wp 4.2.1+hm -> satisfiable by humanmade/facebook-instant-articles-wp[4.2.1+hm].
    - altis/seo 1.0.0 requires humanmade/facebook-instant-articles-wp 4.2.1+hm -> satisfiable by humanmade/facebook-instant-articles-wp[4.2.1+hm].
    - Conclusion: don't install humanmade/facebook-instant-articles-wp 4.2.1+hm|keep humanmade/facebook-instant-articles-wp 4.2.1+hm
```
I _think_ this may be a result of the version number "4.2.1+hm" in https://github.com/humanmade/facebook-instant-articles-wp not being considered a stable release. Do you have any ideas how to change this so that we can install Altis 1.0.0 final without the RC stability flag?

**Comment by rmccue** [comment]
4.2.1+hm should be considered a stable release, so I don't think it's that. https://semver.mwl.be/#!?package=humanmade%2Ffacebook-instant-articles-wp&version=%5E4.2&minimum-stability=stable shows `^4.2` selects `4.2.1+hm` correctly.

Maybe try wiping your composer.lock? Composer sometimes gets confused with updates.

**Comment by rmccue** [comment]
I haven't seen this pop up again and installations seem to be working, so closing as invalid. Feel free to reopen as needed.
