### ISSUE TITLE
robots.txt is loaded from "config" dir, not ".config"

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-seo#27]
Per https://www.altis-dxp.com/resources/docs/getting-started/configuration/ the directory we use for config is `.config`.

The path on this line needs correcting https://github.com/humanmade/altis-seo/blob/master/inc/namespace.php#L94

Acceptance criteria:

- [x] Adding a file called `robots.txt` in the `.config` directory causes the contents of that file to be loaded in the browser at `https://<site url>/robots.txt`

**Comment by dashaluna** [comment]
Question: is it the same issue with SSO module on this line here https://github.com/humanmade/altis-sso/blob/master/inc/saml/namespace.php#L34 as I can see a bit below that line there is `/.config` used https://github.com/humanmade/altis-sso/blob/master/inc/saml/namespace.php#L41

**Comment by rmccue** [comment]
Yeah, we made the same mistake originally with the SSO module; [those lines of code](https://github.com/humanmade/altis-sso/blob/6368bcd8dfafe5fb3891b61d512ef19933a28f7a/inc/saml/namespace.php#L33-L38) are to keep backwards compatibility with the old mistake, and [the other lines](https://github.com/humanmade/altis-sso/blob/6368bcd8dfafe5fb3891b61d512ef19933a28f7a/inc/saml/namespace.php#L40-L41) are for the new style.

We want to apply the same backwards compatibility process for robots.txt I think.
