### ISSUE TITLE
Add built in Image sitemap

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-seo#41]
Now that we have the core WP sitemaps we can build on that value by providing custom sitemaps for specific use cases. Depending on the complexity and variation in requirements the outcome of this might be one of:

- Documentation for building an image sitemap
- An image site map provider class with appropriate hooks / filters documented

The docs for how to construct one are here:

https://support.google.com/webmasters/answer/178636?hl=en

We can either parse post content and add image details inline eg:

```xml
<url>
    <loc>http://example.com/sample.html</loc>
    <image:image>
      <image:loc>http://example.com/image.jpg</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://example.com/photo.jpg</image:loc>
    </image:image>
</url>
```

Or it can be a pure image sitemap.

Other metadata can be specified such as caption etc which can be read from gutenberg blocks, the HTML structure or the attachment post data.

**Comment by jazzsequence** [comment]
Is this still valid if sitemaps are provided by Yoast? Should we use WP sitemaps as a fallback?

**Comment by rmccue** [comment]
Closing as won't do.
