### ISSUE TITLE
Document solution for google site verification

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-seo#5]
More info here https://support.google.com/webmasters/answer/9008080?hl=en

I think the recommended options are the ones that don't rely on PHP running or any other aspect of the system other than the webserver which leaves:

## HTML file upload

The file name is unique each time so not really something that can be accounted for in config, easier just to let the webserver do it's thing and document where to put it.

## DNS record

This option we could possibly support as part of a build step by provisioning Route53 updates but I have a feeling that'd require the domain to be transferred to and managed by us.

**Comment by roborourke** [comment]
@Japh @joehoyle if you have any insights here it'd be appreciated :)

**Comment by joehoyle** [comment]
@roborourke we could just do the HTML file upload at the build step, based off a value in their composer.json too. Would make it marginally easier than creating the file, but it's true, not by much. We should probalby just have a docuentation page on how exactly to do that

**Comment by roborourke** [comment]
Cheers. Updating the issue title to reflect this discussion

**Comment by rmccue** [comment]
Per [Slack discussion](https://hmn.slack.com/archives/C3CKS8LLR/p1559308371041100), a UI field where you can paste the meta tag makes most sense here I think.
