### ISSUE TITLE
Task: Remove Yoast admin UI elements

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-seo#55]
There are additional admin UI elements that should be removed to simplify the admin.

**Acceptance Criteria:**
- ~Hide the "Add related keyphrase" accordion option if not premium (this may need to be done on their end)~
- [x] remove Premium submenu page
- [x] Remove admin bar menu
- [x] If on non-production environments, ignore search engines discouraged notice ("huge SEO issue")
- [x] remove helpscout beacon

**Dev notes**
example code:
```php
add_action( 'admin_init', function() {
	$options = get_option( 'wpseo' );

	// Disable the admin bar menu.
	$options['enable_admin_bar_menu'] = false;
	if ( in_array( Altis\get_environment_type(), [ 'local', 'development' ], true ) ) {
		// Don't display the HUGE SEO issue on local or dev environments.
		$options['ignore_search_engines_discouraged_notice'] = true;
	}
	update_option( 'wpseo', $options );

	// Remove Helpscout.
	add_filter( 'wpseo_helpscout_show_beacon', '__return_false' );

	// Remove the Premium submenu.
	$menu = 'wpseo_dashboard';
	$submenu = 'wpseo_licenses';
	remove_submenu_page( $menu, $submenu );
}, 11 );
```

**Comment by roborourke** [comment]
could probably include staging in that list too for removing the big warning, basically for anything that isn't production.

**Comment by jazzsequence** [comment]
Dropping "Hide the "Add related keyphrase" accordion option if not premium" from the list. Recent internal conversations have concluded that we don't necessarily need to remove absolutely all of the upsells.
