### ISSUE TITLE
Task: Create WP SEO -> Yoast SEO migration scripts

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-seo#56]
Migrate any existing WP SEO data into Yoast SEO. This includes both global settings and per-post meta.

**Acceptance Criteria:**
- [x] Create a migration script hooked to `wp altis migrate` (e.g. `wp altis migrate seo`)
  - [x] Migrate WP SEO option data
  - [x] Migrate WP SEO postmeta

**Dev Notes**
> how does WP SEO store the custom title, description and keywords for a post? How can those be migrated?

Both WP SEO and Yoast SEO store that information in post meta, and each have comparable meta keys for that data. Yoast uses a formula for the SEO title (e.g. `%%title%% %%page%% %%sep%% %%sitename%%`). We could either default to this or migrate existing data in the WP SEO `_meta_title` field to `_yoast_wpseo_title`, which is the Yoast equivalent and only added if the title was manually changed from the default pattern.

![Screen Shot 2021-05-10 at 12 37 13 PM](https://user-images.githubusercontent.com/991511/117707984-7b790a80-b18c-11eb-90a1-be0336aa3b7d.png)

Probably what makes the most sense is to migrate the meta data over if it exists -- WP SEO also has default patterns which would get migrated over as part of the migration process, so the most important information here is the meta descriptions and SEO keywords, which would be unique for each post.

**Comment by roborourke** [comment]
Are you thinking the migration script would run on `wp altis migrate` by default but you could run it individually on `wp altis migrate seo`?

I was thinking `wp altis migrate` can just be a catch-all for everything you'd want to when upgrading from one major version to another so a subcommand isn't strictly necessary.

**Comment by jazzsequence** [comment]
I was mostly thinking of just running it on `wp altis migrate seo` but also hooking it back to `wp altis migrate` makes sense, too.
