### ISSUE TITLE
Task: Remove humanmade/meta-tags

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-seo#57]
The `humanmade/meta-tags` plugin can be replaced by Yoast entirely. The only thing that the Meta Tags plugin supports that is not supported out of the box in the free version of Yoast is `og:article:author` and `og:article:section`. To maintain backwards compatibility, these two tags could be added/ported over manually in our integration code. On the other hand, Yoast adds a _lot_ more data including the ability to have unique meta tags for different social networks (twitter vs facebook).

**Screenshots**

### `humanmade/meta-tags`
![Screen Shot 2021-05-10 at 12 43 30 PM](https://user-images.githubusercontent.com/991511/117709952-c562f000-b18e-11eb-95bb-596dd9d77108.png)

### `yoast/wordpress-seo`
![Screen Shot 2021-05-10 at 12 51 05 PM](https://user-images.githubusercontent.com/991511/117710002-d6abfc80-b18e-11eb-8cac-a05b996f2ff0.png)

**Acceptance Criteria:**
- [x] Remove `humanmade/meta-tags` from `composer.json`
- [x] Add `og:article:author` and `og:article:section` tags to appropriate post headers

**Comment by roborourke** [comment]
Fixed in #57
