### ISSUE TITLE
Replace existing SEO tools with Yoast SEO

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-seo#60]
For Altis v8 and moving forward, we will be using Yoast SEO as our SEO solution by default. There are many parts to this integration including UI changes to remove/hide upsell banners and re-theme to Altis branding, migrating settings and data from WP SEO to Yoast SEO and removing/replacing Altis SEO features with their equivalents that are built into Yoast. 

**Action Items**
- [ ] We need a way to disable/remove/hide the "Add related keyphrase" accordion menu in the edit post metabox

[Sidebar]
![Screen Shot 2021-05-12 at 12 19 35 PM](https://user-images.githubusercontent.com/991511/118028539-6b922f80-b320-11eb-96b0-0e79e0ad0e0e.png)

[Post Meta]
![Screen Shot 2021-05-12 at 12 19 50 PM](https://user-images.githubusercontent.com/991511/118028581-7947b500-b320-11eb-8562-ab3c61ce139c.png)

- [ ] We need _one_ of the randomized (Styled Components) classnames to have a static class
 `.yoast span.yTsQm` -- the wrapper around the styled search result shortcode element
![Screen Shot 2021-05-12 at 12 35 12 PM](https://user-images.githubusercontent.com/991511/118029353-52d64980-b321-11eb-80ea-43c62c771875.png)

**Comment by roborourke** [comment]
FWIW the random class names are hashes of the CSS and component props and come from the https://styled-components.com/ library.

Yoast just need to add static `className` props to their components as well.

**Comment by jazzsequence** [comment]
@rmccue I've added screenshots and more specific details for what we need from the Yoast team (thus far). Do you want to own pinging them and asking for these things or should I drop into the shared Slack channel to ask? Or do they have a better way of filing these (e.g. opening a ticket in their GH repo)?

**Comment by rmccue** [comment]
@jazzsequence Can we split these items from the epic? (Or possibly keep this issue but spin up a new one for the epic given the writeup is already here.)

I can own follow-ups as needed :)

**Comment by jazzsequence** [comment]
@rmccue yep, I wasn't sure if those two things really warranted a separate ticket or if we wanted to just keep them here since they're kinda meta tasks. I'm fine with them being broken out and can own creating the ticket (just copy/paste for the two items we need from the Yoast team).

**Comment by roborourke** [comment]
I believe we can close this out now the migration script is done @rmccue

**Comment by rmccue** [comment]
Neato 👍
