### ISSUE TITLE
Yoast SEO warning is displayed on dev/staging sites

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-seo#68]
Steps to reproduce:
1. Update to latest SEO with Yoast included
2. Open admin
3. Observe warning about site being hidden from search

This warning isn't useful for development and staging environments, and hence should not be shown.

We may want to remove this warning entirely, as private sites will likely also receive it.

<img width="1254" alt="Screen Shot 2021-06-10 at 16 16 47" src="https://user-images.githubusercontent.com/21655/121551164-508e0a80-ca07-11eb-8b35-d9468af1c176.png">

Acceptance criteria:

- [ ] Hide SEO warning on development and staging environments

**Comment by jazzsequence** [comment]
This is one of the acceptance criteria of https://github.com/humanmade/altis-seo/issues/55
