### ISSUE TITLE
Out of the box warnings from Yoast

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-seo#83]
On platform-test, I'm getting the following warnings from Yoast:

<img width="1276" alt="Screen Shot 2021-07-08 at 13 36 05" src="https://user-images.githubusercontent.com/21655/124922606-8ec01f00-dff1-11eb-9e88-04b411093222.png">

**Comment by roborourke** [comment]
Yeah seeing those too. Cheers for the issue.
