### ISSUE TITLE
Yoast Premium installation broken with Altis v8

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-seo#99]
Yoast premium when installed via composer adds the free version of Yoast SEO as a dependency and attempts to load it from the same directory / location.

We need to determine how best to load Yoast SEO Premium alongside our modifications for the installation location and loading for the Yoast SEO free version.

**Comment by kadamwhite** [comment]
We're experimenting with this shim (committed to `plugins/wordpress-seo/wp-seo.php` as a manual workaround for now. I believe a file needs to exist at this path for Yoast SEO Premium to detect the free version of the plugin, and at present I haven't encountered any downsides to loading the rest of the plugin logic out of `vendor`.

```php
<?php
/**
 * Yoast SEO Plugin LOADING SHIM.
 *
 * @wordpress-plugin
 * Plugin Name: Yoast SEO
 * Version:     16.9
 * Description: Loads Yoast SEO from the copy bundled with Altis.
 */

require_once Altis\ROOT_DIR . '/vendor/yoast/wordpress-seo/wp-seo.php';

```
Note that the shim does need to be activated as a plugin.
